//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_designed_Dictionary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("New_designed_Dictionary.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example(s).
        /// </summary>
        public static string CheckBox_SearchByExample {
            get {
                return ResourceManager.GetString("CheckBox_SearchByExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meaning(s).
        /// </summary>
        public static string CheckBox_SearchByMeaning {
            get {
                return ResourceManager.GetString("CheckBox_SearchByMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note(s).
        /// </summary>
        public static string CheckBox_SearchByNote {
            get {
                return ResourceManager.GetString("CheckBox_SearchByNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source(s).
        /// </summary>
        public static string CheckBox_SearchBySource {
            get {
                return ResourceManager.GetString("CheckBox_SearchBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag(s).
        /// </summary>
        public static string CheckBox_SearchByTag {
            get {
                return ResourceManager.GetString("CheckBox_SearchByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search while typing.
        /// </summary>
        public static string CheckBox_SearchOnTyping {
            get {
                return ResourceManager.GetString("CheckBox_SearchOnTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        public static string Label_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Label_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents:.
        /// </summary>
        public static string Label_Contents {
            get {
                return ResourceManager.GetString("Label_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        public static string Label_Example {
            get {
                return ResourceManager.GetString("Label_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Label_Export_Title {
            get {
                return ResourceManager.GetString("Label_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning:.
        /// </summary>
        public static string Label_Meaning {
            get {
                return ResourceManager.GetString("Label_Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Label_Note {
            get {
                return ResourceManager.GetString("Label_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dict. units: .
        /// </summary>
        public static string Label_NumberOfUnits {
            get {
                return ResourceManager.GetString("Label_NumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Label_Source {
            get {
                return ResourceManager.GetString("Label_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of unit:.
        /// </summary>
        public static string Label_TypeOfUnit {
            get {
                return ResourceManager.GetString("Label_TypeOfUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the contents....
        /// </summary>
        public static string Placeholder_Contents {
            get {
                return ResourceManager.GetString("Placeholder_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the example....
        /// </summary>
        public static string Placeholder_Example {
            get {
                return ResourceManager.GetString("Placeholder_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the meaning....
        /// </summary>
        public static string Placeholder_Meaning {
            get {
                return ResourceManager.GetString("Placeholder_Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your note....
        /// </summary>
        public static string Placeholder_Note {
            get {
                return ResourceManager.GetString("Placeholder_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search sources....
        /// </summary>
        public static string Placeholder_SearchSources {
            get {
                return ResourceManager.GetString("Placeholder_SearchSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search word units....
        /// </summary>
        public static string Placeholder_SearchWordUnits {
            get {
                return ResourceManager.GetString("Placeholder_SearchWordUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in search:.
        /// </summary>
        public static string Section_Id_IncludeProperties {
            get {
                return ResourceManager.GetString("Section_Id_IncludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Own Dictionary.
        /// </summary>
        public static string Title_Main_TopMiddle {
            get {
                return ResourceManager.GetString("Title_Main_TopMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search settings.
        /// </summary>
        public static string Title_Modal_SearchSettings {
            get {
                return ResourceManager.GetString("Title_Modal_SearchSettings", resourceCulture);
            }
        }
    }
}
