//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_designed_Dictionary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("New_designed_Dictionary.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#AdjectiveClass.
        /// </summary>
        public static string Ontology_Adjective_Class {
            get {
                return ResourceManager.GetString("Ontology_Adjective_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#.
        /// </summary>
        public static string Ontology_Base {
            get {
                return ResourceManager.GetString("Ontology_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#Example.
        /// </summary>
        public static string Ontology_Example {
            get {
                return ResourceManager.GetString("Ontology_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#PartOfSpeech.
        /// </summary>
        public static string Ontology_PartOfSpeech {
            get {
                return ResourceManager.GetString("Ontology_PartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Folders\SampleSave.owl.
        /// </summary>
        public static string Ontology_Path {
            get {
                return ResourceManager.GetString("Ontology_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#AppliesUnit.
        /// </summary>
        public static string Ontology_Property_AppliesUnit {
            get {
                return ResourceManager.GetString("Ontology_Property_AppliesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#IsApplied.
        /// </summary>
        public static string Ontology_Property_IsApplied {
            get {
                return ResourceManager.GetString("Ontology_Property_IsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#IsProvidedBy.
        /// </summary>
        public static string Ontology_Property_IsProvidedBy {
            get {
                return ResourceManager.GetString("Ontology_Property_IsProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#IsProvidedBy.
        /// </summary>
        public static string Ontology_Property_IsProvidedBy3 {
            get {
                return ResourceManager.GetString("Ontology_Property_IsProvidedBy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#IsProvidedBy.
        /// </summary>
        public static string Ontology_Property_IsProvidedBy4 {
            get {
                return ResourceManager.GetString("Ontology_Property_IsProvidedBy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#IsProvidedBy.
        /// </summary>
        public static string Ontology_Property_IsProvidedBy5 {
            get {
                return ResourceManager.GetString("Ontology_Property_IsProvidedBy5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#Provides.
        /// </summary>
        public static string Ontology_Property_Provides {
            get {
                return ResourceManager.GetString("Ontology_Property_Provides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#UsedSource.
        /// </summary>
        public static string Ontology_Source {
            get {
                return ResourceManager.GetString("Ontology_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#Tag.
        /// </summary>
        public static string Ontology_Tag {
            get {
                return ResourceManager.GetString("Ontology_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#WordUnit.
        /// </summary>
        public static string Ontology_WordUnit {
            get {
                return ResourceManager.GetString("Ontology_WordUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdf: &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;
        ///PREFIX owl: &lt;http://www.w3.org/2002/07/owl#&gt;
        ///PREFIX rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt;
        ///PREFIX xsd: &lt;http://www.w3.org/2001/XMLSchema#&gt;
        ///PREFIX vocabulary: &lt;http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#&gt;.
        /// </summary>
        public static string SPARQL_Namespace {
            get {
                return ResourceManager.GetString("SPARQL_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Alexander\Desktop\GoogleNews-vectors-negative300.bin.
        /// </summary>
        public static string Word2Vec_bin_file {
            get {
                return ResourceManager.GetString("Word2Vec_bin_file", resourceCulture);
            }
        }
    }
}
