//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_designed_Dictionary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("New_designed_Dictionary.Resources.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdf: &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt; 
        ///PREFIX owl: &lt;http://www.w3.org/2002/07/owl#&gt; 
        ///PREFIX rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt; 
        ///PREFIX xsd: &lt;http://www.w3.org/2001/XMLSchema#&gt; 
        ///PREFIX vocabulary: &lt;http://www.semanticweb.org/alexander/ontologies/2018/11/Dictionary#&gt;.
        /// </summary>
        public static string PREFIXES {
            get {
                return ResourceManager.GetString("PREFIXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ?source
        ///	WHERE { ?source a vocabulary:UsedSource.
        ///}.
        /// </summary>
        public static string Query_Indiv_Sources {
            get {
                return ResourceManager.GetString("Query_Indiv_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ?tags
        ///	WHERE { ?tags a vocabulary:Tag.
        ///}.
        /// </summary>
        public static string Query_Indiv_Tags {
            get {
                return ResourceManager.GetString("Query_Indiv_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///	WHERE { ?word a vocabulary:WordUnit.
        ///	OPTIONAL { ?word vocabulary:HasMeaning ?meaning . }
        ///	OPTIONAL { ?word vocabulary:HasExample ?example . }
        ///	OPTIONAL { ?word vocabulary:HasNote ?note . }
        ///	OPTIONAL { ?word vocabulary:IsProvidedBy ?source . }
        ///	FILTER(REGEX(STR(?word), &quot;X&quot;, &quot;i&quot;))
        ///}.
        /// </summary>
        public static string Query_Indiv_WordUnit {
            get {
                return ResourceManager.GetString("Query_Indiv_WordUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///	WHERE { ?word a vocabulary:WordUnit.
        ///	OPTIONAL { ?word vocabulary:HasMeaning ?meaning . }
        ///	OPTIONAL { ?word vocabulary:HasExample ?example . }
        ///	OPTIONAL { ?word vocabulary:HasNote ?note . }
        ///	FILTER(REGEX(STR(?word), &quot;X&quot;, &quot;i&quot;))
        ///}.
        /// </summary>
        public static string Query_Indiv_WordUnit_By_Name {
            get {
                return ResourceManager.GetString("Query_Indiv_WordUnit_By_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ?word
        ///	WHERE { ?word a vocabulary:WordUnit.
        ///}.
        /// </summary>
        public static string Query_Indiv_WordUnit_Name {
            get {
                return ResourceManager.GetString("Query_Indiv_WordUnit_Name", resourceCulture);
            }
        }
    }
}
